name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CC: gcc-11
  CXX: g++-11

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Configure and build client
      working-directory: ${{github.workspace}}
      shell: bash
      run: chmod 777 ./script/build_client.sh && ./script/build_client.sh $BUILD_TYPE

    - name: Configure and build server
      working-directory: ${{github.workspace}}
      shell: bash
      run: chmod 777 ./script/build_server.sh && ./script/build_server.sh $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --preset conan-debug

    - name: Lcov
      working-directory:  ${{github.workspace}}/build
      shell: bash
      run: lcov --capture --directory $GITHUB_WORKSPACE -o coverage.info --no-external

    - name: Upload to Codecov.io
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov